### ISSUE TITLE
Dead Link in Fahrplan

### ISSUE THREAD

**Issue by birdy1976** [zeteco/badge#1]
The link „Badge im Wiki“ [1] in „ZeTeCo Badge“ [2] should point to [3].

[1] http://badge.zeteco.ch/
[2] https://fahrplan.zeteco.ch/events/64.html
[3] https://wiki.zeteco.ch/wiki/Badge

**Comment by signalwerk** [comment]
@birdy1976 danke für dein feedback. da war was krumm. sollte aber nun wieder gehen! sobald tony mir noch die badge-materialien gegeben hat, werde ich die hier auch noch hoch laden.
